---

- name: place desktop menu icons
  copy:
    src: "{{ item }}"
    dest: /usr/share/applications
    owner: root
    group: root
    mode: 0644
  with_items:
    - rstudio.desktop
    - matlab.desktop
    - jupyter.desktop
    - anaconda.desktop
